

format_patient = [
    {   'Begin': '1',
        'Code org': 'Vektis',
        'Codetabel': 'AGB register',
        'DDID': '1430',
        'Eind': '8',
        'Lengte': '8',
        'Naam': 'Declarerende instelling',
        'Patroon': 'NNNNNNNN',
        'Sleutel': 'PK',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '9',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1431',
        'Eind': '10',
        'Lengte': '2',
        'Naam': 'Instelling volgnr DIS',
        'Patroon': 'NN',
        'Sleutel': 'PK',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '11',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1432',
        'Eind': '25',
        'Lengte': '15',
        'Naam': 'Koppelnummer',
        'Patroon': '',
        'Sleutel': 'PK',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '26',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1433',
        'Eind': '50',
        'Lengte': '25',
        'Naam': 'Naam_1',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '51',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1434',
        'Eind': '60',
        'Lengte': '10',
        'Naam': 'Naam voorvoegsel_1',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '61',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1435',
        'Eind': '61',
        'Lengte': '1',
        'Naam': 'Naamcode_1',
        'Patroon': '1 of 2',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '62',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1436',
        'Eind': '86',
        'Lengte': '25',
        'Naam': 'Naam_2',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '87',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1437',
        'Eind': '96',
        'Lengte': '10',
        'Naam': 'Naam voorvoegsel_2',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '97',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1438',
        'Eind': '97',
        'Lengte': '1',
        'Naam': 'Naamcode_2',
        'Patroon': '1 of 2 of [spatie]',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'CV'},
    {   'Begin': '98',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1439',
        'Eind': '103',
        'Lengte': '6',
        'Naam': 'Voorletters',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '104',
        'Code org': 'postcode.nl',
        'Codetabel': '4-positiepostcodetabel (4PP)',
        'DDID': '1440',
        'Eind': '109',
        'Lengte': '6',
        'Naam': 'Postcode',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'CV'},
    {   'Begin': '110',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1441',
        'Eind': '114',
        'Lengte': '5',
        'Naam': 'Huisnummer',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'O'},
    {   'Begin': '115',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1442',
        'Eind': '118',
        'Lengte': '4',
        'Naam': 'Huisnummer toevoeging',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '119',
        'Code org': 'ISO',
        'Codetabel': 'ISO 3166-1',
        'DDID': '1443',
        'Eind': '120',
        'Lengte': '2',
        'Naam': 'Landcode',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '121',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1444',
        'Eind': '128',
        'Lengte': '8',
        'Naam': 'Geboortedatum',
        'Patroon': 'YYYYMMDD',
        'Sleutel': '',
        'Type': 'D',
        'Verplicht': 'V'},
    {   'Begin': '129',
        'Code org': 'Vektis',
        'Codetabel': 'Geslacht (COD046)',
        'DDID': '1445',
        'Eind': '129',
        'Lengte': '1',
        'Naam': 'Geslacht',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'V'},
    {   'Begin': '130',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1446',
        'Eind': '138',
        'Lengte': '9',
        'Naam': 'Burgerservicenummer',
        'Patroon': '9xN',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '139',
        'Code org': '',
        'Codetabel': '',
        'DDID': '3182',
        'Eind': '144',
        'Lengte': '6',
        'Naam': 'Eerste inschrijfdatum',
        'Patroon': 'YYYYMM',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '145',
        'Code org': '',
        'Codetabel': '',
        'DDID': '3183',
        'Eind': '150',
        'Lengte': '6',
        'Naam': 'Laatste uitschrijfdatum',
        'Patroon': 'YYYYMM',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '151',
        'Code org': '',
        'Codetabel': '',
        'DDID': '4113',
        'Eind': '170',
        'Lengte': '20',
        'Naam': 'Reserve',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'}]

format_zorgtraject =  [
    {   'Begin': '1',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1449',
        'Eind': '20',
        'Lengte': '20',
        'Naam': 'Zorgtrajectnummer',
        'Patroon': '',
        'Sleutel': 'PK',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '21',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1450',
        'Eind': '21',
        'Lengte': '1',
        'Naam': 'Status vlag',
        'Patroon': "[spatie] of 'V'",
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '22',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1451',
        'Eind': '29',
        'Lengte': '8',
        'Naam': 'Begindatum zorgtraject',
        'Patroon': 'YYYYMMDD',
        'Sleutel': '',
        'Type': 'D',
        'Verplicht': 'V'},
    {   'Begin': '30',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1452',
        'Eind': '37',
        'Lengte': '8',
        'Naam': 'Einddatum zorgtraject',
        'Patroon': 'YYYYMMDD',
        'Sleutel': '',
        'Type': 'D',
        'Verplicht': 'O'},
    {   'Begin': '38',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1453',
        'Eind': '52',
        'Lengte': '15',
        'Naam': 'Koppelnummer',
        'Patroon': '',
        'Sleutel': 'FK',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '53',
        'Code org': 'Vektis',
        'Codetabel': 'AGB register',
        'DDID': '1454',
        'Eind': '60',
        'Lengte': '8',
        'Naam': 'Verwijzende instelling',
        'Patroon': 'NNNNNNNN',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '61',
        'Code org': 'Vektis',
        'Codetabel': 'Zorgverlenersspecificatie, COD016',
        'DDID': '1455',
        'Eind': '64',
        'Lengte': '4',
        'Naam': 'Soort verwijzer',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '65',
        'Code org': 'NZa',
        'Codetabel': 'CL_DIAGNOSE_GGZ',
        'DDID': '1456',
        'Eind': '84',
        'Lengte': '20',
        'Naam': 'Primaire diagnosecode',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'CV'},
    {   'Begin': '85',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1457',
        'Eind': '85',
        'Lengte': '1',
        'Naam': 'Primaire diagnose; trekken van',
        'Patroon': "[spatie] of 'J'",
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '86',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1458',
        'Eind': '93',
        'Lengte': '8',
        'Naam': 'Primaire diagnosedatum',
        'Patroon': 'YYYYMMDD',
        'Sleutel': '',
        'Type': 'D',
        'Verplicht': 'CV'},
    {   'Begin': '94',
        'Code org': 'NZa',
        'Codetabel': 'CL_D5_DIAGNOSE',
        'DDID': '4168',
        'Eind': '123',
        'Lengte': '30',
        'Naam': 'Primaire diagnosecode DSM-5',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'CV'},
    {   'Begin': '124',
        'Code org': '',
        'Codetabel': '',
        'DDID': '4098',
        'Eind': '131',
        'Lengte': '8',
        'Naam': 'Verwijsdatum',
        'Patroon': 'YYYYMMDD',
        'Sleutel': '',
        'Type': 'D',
        'Verplicht': 'O'},
    {   'Begin': '132',
        'Code org': '',
        'Codetabel': '',
        'DDID': '4105',
        'Eind': '151',
        'Lengte': '20',
        'Naam': 'Reserve',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'}]

format_pakbon = [
    {   'Begin': '1',
        'Code org': 'Vektis',
        'Codetabel': 'AGB register',
        'DDID': '1534',
        'Eind': '8',
        'Lengte': '8',
        'Naam': 'Declarerende instelling',
        'Patroon': 'NNNNNNNN',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '9',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1535',
        'Eind': '10',
        'Lengte': '2',
        'Naam': 'Instelling volgnr DIS',
        'Patroon': 'NN',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '11',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1536',
        'Eind': '14',
        'Lengte': '4',
        'Naam': 'Versienummer GA',
        'Patroon': 'NN.N',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '15',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1537',
        'Eind': '22',
        'Lengte': '8',
        'Naam': 'Creatiedatum',
        'Patroon': 'YYYYMMDD',
        'Sleutel': '',
        'Type': 'D',
        'Verplicht': 'V'},
    {   'Begin': '23',
        'Code org': '',
        'Codetabel': '',
        'DDID': '3006',
        'Eind': '24',
        'Lengte': '2',
        'Naam': 'Volgnummer',
        'Patroon': 'NN',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '25',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1538',
        'Eind': '72',
        'Lengte': '48',
        'Naam': 'Zipfilenaam',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '73',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1539',
        'Eind': '87',
        'Lengte': '15',
        'Naam': 'Softwareleverancier',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '88',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1540',
        'Eind': '102',
        'Lengte': '15',
        'Naam': 'Softwarepakket',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '103',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1541',
        'Eind': '117',
        'Lengte': '15',
        'Naam': 'Softwareversie',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '118',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1542',
        'Eind': '124',
        'Lengte': '7',
        'Naam': 'Aantal patient',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'V'},
    {   'Begin': '125',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1543',
        'Eind': '131',
        'Lengte': '7',
        'Naam': 'Aantal zorgtraject',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'V'},
    {   'Begin': '132',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1544',
        'Eind': '138',
        'Lengte': '7',
        'Naam': 'Aantal DBC-traject',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'V'},
    {   'Begin': '139',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1545',
        'Eind': '145',
        'Lengte': '7',
        'Naam': 'Aantal diagnose',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'V'},
    {   'Begin': '146',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1546',
        'Eind': '152',
        'Lengte': '7',
        'Naam': 'Aantal geleverd zorgprofiel tijdschrijven',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'V'},
    {   'Begin': '153',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1547',
        'Eind': '159',
        'Lengte': '7',
        'Naam': 'Aantal geleverd zorgprofiel dagbesteding',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'V'},
    {   'Begin': '160',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1548',
        'Eind': '166',
        'Lengte': '7',
        'Naam': 'Aantal geleverd zorgprofiel verblijfsdagen',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'V'},
    {   'Begin': '167',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1549',
        'Eind': '173',
        'Lengte': '7',
        'Naam': 'Aantal geleverd zorgprofiel verrichtingen',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'V'},
    {   'Begin': '174',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1550',
        'Eind': '180',
        'Lengte': '7',
        'Naam': 'Aantal overige verrichting',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'V'},
    {   'Begin': '181',
        'Code org': '',
        'Codetabel': '',
        'DDID': '3001',
        'Eind': '194',
        'Lengte': '14',
        'Naam': 'Gebruikersnaam',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '195',
        'Code org': 'Kamer van Koophandel',
        'Codetabel': 'KvK registratie',
        'DDID': '3195',
        'Eind': '202',
        'Lengte': '8',
        'Naam': 'Kamer van Koophandelnummer',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '203',
        'Code org': 'Kamer van Koophandel',
        'Codetabel': 'KvK registratie',
        'DDID': '4165',
        'Eind': '214',
        'Lengte': '12',
        'Naam': 'Vestigingsnummer',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'}]

format_diagnose = [
    {   'Begin': '1',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1481',
        'Eind': '20',
        'Lengte': '20',
        'Naam': 'DBC-trajectnummer',
        'Patroon': '',
        'Sleutel': 'PK, FK',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '21',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1482',
        'Eind': '28',
        'Lengte': '8',
        'Naam': 'Diagnosedatum',
        'Patroon': 'YYYYMMDD',
        'Sleutel': '',
        'Type': 'D',
        'Verplicht': 'V'},
    {   'Begin': '29',
        'Code org': 'NZa',
        'Codetabel': 'CL_DIAGNOSE_GGZ',
        'DDID': '1483',
        'Eind': '48',
        'Lengte': '20',
        'Naam': 'Diagnosecode',
        'Patroon': '',
        'Sleutel': 'PK',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '49',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1484',
        'Eind': '49',
        'Lengte': '1',
        'Naam': 'Trekken van',
        'Patroon': "[spatie] of 'J'",
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '50',
        'Code org': 'NZa',
        'Codetabel': 'CL_D5_DIAGNOSE',
        'DDID': '4167',
        'Eind': '79',
        'Lengte': '30',
        'Naam': 'Diagnosecode DSM-5',
        'Patroon': '',
        'Sleutel': 'PK',
        'Type': 'AN',
        'Verplicht': 'CV'},
    {   'Begin': '80',
        'Code org': '',
        'Codetabel': '',
        'DDID': '4104',
        'Eind': '99',
        'Lengte': '20',
        'Naam': 'Reserve',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'}]

format_dbctraject = [
    {   'Begin': '1',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1462',
        'Eind': '20',
        'Lengte': '20',
        'Naam': 'DBC-trajectnummer',
        'Patroon': '',
        'Sleutel': 'PK',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '21',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1463',
        'Eind': '21',
        'Lengte': '1',
        'Naam': 'Status vlag',
        'Patroon': "[spatie] of 'V'",
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '22',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1464',
        'Eind': '41',
        'Lengte': '20',
        'Naam': 'Zorgtrajectnummer',
        'Patroon': '',
        'Sleutel': 'FK',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '42',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1465',
        'Eind': '49',
        'Lengte': '8',
        'Naam': 'Begindatum DBC-traject',
        'Patroon': 'YYYYMMDD',
        'Sleutel': '',
        'Type': 'D',
        'Verplicht': 'V'},
    {   'Begin': '50',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1466',
        'Eind': '57',
        'Lengte': '8',
        'Naam': 'Einddatum DBC-traject',
        'Patroon': 'YYYYMMDD',
        'Sleutel': '',
        'Type': 'D',
        'Verplicht': 'V'},
    {   'Begin': '58',
        'Code org': 'Vektis',
        'Codetabel': 'AGB register',
        'DDID': '4091',
        'Eind': '65',
        'Lengte': '8',
        'Naam': '1e hoofdbehandelaar',
        'Patroon': 'NNNNNNNN',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'CV'},
    {   'Begin': '66',
        'Code org': 'NZa',
        'Codetabel': 'CL_HOOFDBEROEPEN_GGZ',
        'DDID': '4093',
        'Eind': '85',
        'Lengte': '20',
        'Naam': 'Beroepcode 1e hoofdbehandelaar',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'CV'},
    {   'Begin': '86',
        'Code org': 'Vektis',
        'Codetabel': 'AGB register',
        'DDID': '4092',
        'Eind': '93',
        'Lengte': '8',
        'Naam': '2e hoofdbehandelaar',
        'Patroon': 'NNNNNNNN',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'CV'},
    {   'Begin': '94',
        'Code org': 'NZa',
        'Codetabel': 'CL_HOOFDBEROEPEN_GGZ',
        'DDID': '4094',
        'Eind': '113',
        'Lengte': '20',
        'Naam': 'Beroepcode 2e hoofdbehandelaar',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'CV'},
    {   'Begin': '114',
        'Code org': '',
        'Codetabel': '',
        'DDID': '4171',
        'Eind': '114',
        'Lengte': '1',
        'Naam': 'Experimenteerruimte',
        'Patroon': "'J', 'N', Null",
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '115',
        'Code org': 'Vektis',
        'Codetabel': 'COD327-VEK1 (volwassenen)',
        'DDID': '4095',
        'Eind': '116',
        'Lengte': '2',
        'Naam': 'Verwijstype/code (zelf)verwijzer',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '117',
        'Code org': 'Vektis',
        'Codetabel': 'AGB register',
        'DDID': '4146',
        'Eind': '124',
        'Lengte': '8',
        'Naam': 'Verwijzer',
        'Patroon': 'NNNNNNNN',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'CV'},
    {   'Begin': '125',
        'Code org': 'Vektis',
        'Codetabel': 'UZOVI register',
        'DDID': '1467',
        'Eind': '128',
        'Lengte': '4',
        'Naam': 'Zorgverzekeraarcode',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '129',
        'Code org': 'NZa',
        'Codetabel': 'CL_ZORGTYPE_GGZ',
        'DDID': '1468',
        'Eind': '148',
        'Lengte': '20',
        'Naam': 'Zorgtypecode',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '149',
        'Code org': 'NZa',
        'Codetabel': 'CL_CIRCUIT_GGZ',
        'DDID': '1469',
        'Eind': '168',
        'Lengte': '20',
        'Naam': 'Circuitcode',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '169',
        'Code org': 'NZa',
        'Codetabel': 'CL_REDENSLUITEN_GGZ',
        'DDID': '1470',
        'Eind': '188',
        'Lengte': '20',
        'Naam': 'DBC Reden sluiten code',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '189',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1471',
        'Eind': '199',
        'Lengte': '11',
        'Naam': 'Verkoopprijs DBC',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'CV'},
    {   'Begin': '200',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1472',
        'Eind': '200',
        'Lengte': '1',
        'Naam': 'Nieuwe pati\xc3\xabnt',
        'Patroon': "'J', 'N', [spatie]",
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '201',
        'Code org': 'NZa',
        'Codetabel': 'CL_PRODUCTGROEP_GGZ',
        'DDID': '1473',
        'Eind': '206',
        'Lengte': '6',
        'Naam': 'Productgroepcode',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '207',
        'Code org': 'NZa',
        'Codetabel': 'CL_PRESTATIECODE_GGZ',
        'DDID': '1474',
        'Eind': '218',
        'Lengte': '12',
        'Naam': 'Prestatiecode',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '219',
        'Code org': 'NZa',
        'Codetabel': 'CL_TARIEF_GGZ',
        'DDID': '1475',
        'Eind': '224',
        'Lengte': '6',
        'Naam': 'Declaratiecode',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '225',
        'Code org': 'NZa',
        'Codetabel': 'CL_TARIEF_GGZ',
        'DDID': '1476',
        'Eind': '235',
        'Lengte': '11',
        'Naam': 'DBC-tarief',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'V'},
    {   'Begin': '236',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1477',
        'Eind': '246',
        'Lengte': '11',
        'Naam': 'Verrekenbedrag',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'V'},
    {   'Begin': '247',
        'Code org': '',
        'Codetabel': '',
        'DDID': '2144',
        'Eind': '254',
        'Lengte': '8',
        'Naam': 'Declaratiedatum',
        'Patroon': 'YYYYMMDD',
        'Sleutel': '',
        'Type': 'D',
        'Verplicht': 'O'},
    {   'Begin': '255',
        'Code org': 'NZa',
        'Codetabel': 'CL_TARIEF_GGZ',
        'DDID': '3217',
        'Eind': '265',
        'Lengte': '11',
        'Naam': 'NHC-tarief behandeldeel',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'V'},
    {   'Begin': '266',
        'Code org': '',
        'Codetabel': '',
        'DDID': '3218',
        'Eind': '276',
        'Lengte': '11',
        'Naam': 'NHC totaal gedeclareerd bedrag',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'V'},
    {   'Begin': '277',
        'Code org': '',
        'Codetabel': '',
        'DDID': '4106',
        'Eind': '279',
        'Lengte': '3',
        'Naam': 'Leeftijd',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'O'},
    {   'Begin': '280',
        'Code org': '',
        'Codetabel': '',
        'DDID': '4103',
        'Eind': '299',
        'Lengte': '20',
        'Naam': 'Reserve',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'}]

format_geleverd_zorgprofiel_tijdschrijven = [{   'Begin': '1',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1488',
        'Eind': '20',
        'Lengte': '20',
        'Naam': 'DBC-trajectnummer',
        'Patroon': '',
        'Sleutel': 'FK',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '21',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1489',
        'Eind': '40',
        'Lengte': '20',
        'Naam': 'Activiteitnummer',
        'Patroon': '',
        'Sleutel': 'PK',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '41',
        'Code org': 'NZa',
        'Codetabel': 'CL_ACTIVITEIT_GGZ',
        'DDID': '1490',
        'Eind': '60',
        'Lengte': '20',
        'Naam': 'Activiteitcode',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '61',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1491',
        'Eind': '68',
        'Lengte': '8',
        'Naam': 'Activiteitdatum',
        'Patroon': 'YYYYMMDD',
        'Sleutel': '',
        'Type': 'D',
        'Verplicht': 'V'},
    {   'Begin': '69',
        'Code org': 'Vektis',
        'Codetabel': 'AGB register',
        'DDID': '4135',
        'Eind': '76',
        'Lengte': '8',
        'Naam': 'Behandelaarcode',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '77',
        'Code org': 'NZa',
        'Codetabel': 'CL_BEROEP_GGZ of\nCL_HOOFDBEROEPEN_GGZ',
        'DDID': '1492',
        'Eind': '96',
        'Lengte': '20',
        'Naam': 'Beroepcode',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'V'},
    {   'Begin': '97',
        'Code org': '',
        'Codetabel': '',
        'DDID': '4136',
        'Eind': '97',
        'Lengte': '1',
        'Naam': 'Hoofdbehandelaar',
        'Patroon': "'J' of 'N' of [spatie]",
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'CV'},
    {   'Begin': '98',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1493',
        'Eind': '103',
        'Lengte': '6',
        'Naam': 'Direct pati\xc3\xabntgebonden tijd (minuten)',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'V'},
    {   'Begin': '104',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1495',
        'Eind': '109',
        'Lengte': '6',
        'Naam': 'Indirect pati\xc3\xabntgebonden tijd -\nalgemeen (minuten)',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'V'},
    {   'Begin': '110',
        'Code org': '',
        'Codetabel': '',
        'DDID': '1494',
        'Eind': '115',
        'Lengte': '6',
        'Naam': 'Indirect pati\xc3\xabntgebonden tijd - reistijd\n(minuten)',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'V'},
    {   'Begin': '116',
        'Code org': 'Vektis',
        'Codetabel': 'AGB register',
        'DDID': '4142',
        'Eind': '123',
        'Lengte': '8',
        'Naam': 'Uitvoerende instelling',
        'Patroon': 'NNNNNNNN',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '124',
        'Code org': '',
        'Codetabel': '',
        'DDID': '3002',
        'Eind': '127',
        'Lengte': '4',
        'Naam': 'Postwijk',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'O'},
    {   'Begin': '128',
        'Code org': '',
        'Codetabel': '',
        'DDID': '3188',
        'Eind': '131',
        'Lengte': '4',
        'Naam': 'Deelfactor groepscontacten',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'N',
        'Verplicht': 'O'},
    {   'Begin': '132',
        'Code org': '',
        'Codetabel': '',
        'DDID': '3189',
        'Eind': '151',
        'Lengte': '20',
        'Naam': 'Afspraaknummer/code',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'},
    {   'Begin': '152',
        'Code org': '',
        'Codetabel': '',
        'DDID': '4128',
        'Eind': '171',
        'Lengte': '20',
        'Naam': 'Reserve',
        'Patroon': '',
        'Sleutel': '',
        'Type': 'AN',
        'Verplicht': 'O'}]
