

format_patient = [
    {'Begin': '1',
  'Code org': 'Vektis',
  'Codetabel': 'AGB (praktijk of instellingscode)',
  'DDID': '3232',
  'Eind': '8',
  'Lengte': '8',
  'Naam': 'Declarerende instelling',
  'Patroon': '',
  'Sleutel': 'PK',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '9',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3343',
  'Eind': '10',
  'Lengte': '2',
  'Naam': 'Instelling volgnr DIS',
  'Patroon': 'NN',
  'Sleutel': 'PK',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '11',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3340',
  'Eind': '25',
  'Lengte': '15',
  'Naam': 'Koppelnummer',
  'Patroon': '',
  'Sleutel': 'PK',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '26',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3235',
  'Eind': '50',
  'Lengte': '25',
  'Naam': 'Naam_1',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '51',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3236',
  'Eind': '60',
  'Lengte': '10',
  'Naam': 'Naam voorvoegsel_1',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'O'},
 {'Begin': '61',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3237',
  'Eind': '61',
  'Lengte': '1',
  'Naam': 'Naamcode_1',
  'Patroon': '1 of 2',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '62',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3238',
  'Eind': '86',
  'Lengte': '25',
  'Naam': 'Naam_2',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'O'},
 {'Begin': '87',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3336',
  'Eind': '96',
  'Lengte': '10',
  'Naam': 'Naam voorvoegsel_2',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'O'},
 {'Begin': '97',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3240',
  'Eind': '97',
  'Lengte': '1',
  'Naam': 'Naamcode_2',
  'Patroon': '1 of 2 of [spatie]',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'CV'},
 {'Begin': '98',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3241',
  'Eind': '103',
  'Lengte': '6',
  'Naam': 'Voorletters',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '104',
  'Code org': 'postcode.nl',
  'Codetabel': '4-positie codetabel',
  'DDID': '3242',
  'Eind': '109',
  'Lengte': '6',
  'Naam': 'Postcode',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'CV'},
 {'Begin': '110',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3335',
  'Eind': '114',
  'Lengte': '5',
  'Naam': 'Huisnummer',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'N',
  'Verplicht': 'O'},
 {'Begin': '115',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3244',
  'Eind': '118',
  'Lengte': '4',
  'Naam': 'Huisnummer toevoeging',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'O'},
 {'Begin': '119',
  'Code org': 'ISO',
  'Codetabel': 'ISO 3166-1',
  'DDID': '3338',
  'Eind': '120',
  'Lengte': '2',
  'Naam': 'Landcode',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '121',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3246',
  'Eind': '128',
  'Lengte': '8',
  'Naam': 'Geboortedatum',
  'Patroon': 'YYYYMMDD',
  'Sleutel': '',
  'Type': 'D',
  'Verplicht': 'V'},
 {'Begin': '129',
  'Code org': 'Vektis',
  'Codetabel': 'Geslacht (COD046)',
  'DDID': '3247',
  'Eind': '129',
  'Lengte': '1',
  'Naam': 'Geslacht',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'N',
  'Verplicht': 'V'},
 {'Begin': '130',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3248',
  'Eind': '138',
  'Lengte': '9',
  'Naam': 'Burgerservicenummer',
  'Patroon': '9xN',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '139',
  'Code org': '',
  'Codetabel': '',
  'DDID': '4059',
  'Eind': '158',
  'Lengte': '20',
  'Naam': 'Reserve',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'O'}]

format_behandeltraject = [{'Begin': '1',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3257',
  'Eind': '20',
  'Lengte': '20',
  'Naam': 'Behandeltrajectnummer',
  'Patroon': '',
  'Sleutel': 'PK',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '21',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3258',
  'Eind': '35',
  'Lengte': '15',
  'Naam': 'Koppelnummer',
  'Patroon': '',
  'Sleutel': 'FK',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '36',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3259',
  'Eind': '36',
  'Lengte': '1',
  'Naam': 'Status vlag',
  'Patroon': "[spatie] of 'V'",
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'O'},
 {'Begin': '37',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3262',
  'Eind': '44',
  'Lengte': '8',
  'Naam': 'Begindatum behandeltraject',
  'Patroon': 'YYYYMMDD',
  'Sleutel': '',
  'Type': 'D',
  'Verplicht': 'V'},
 {'Begin': '45',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3263',
  'Eind': '52',
  'Lengte': '8',
  'Naam': 'Einddatum behandeltraject',
  'Patroon': 'YYYYMMDD',
  'Sleutel': '',
  'Type': 'D',
  'Verplicht': 'V'},
 {'Begin': '53',
  'Code org': 'Vektis',
  'Codetabel': 'AGB (persoonlijke zorgverleners code)',
  'DDID': '3358',
  'Eind': '60',
  'Lengte': '8',
  'Naam': '1e hoofdbehandelaar',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '61',
  'Code org': 'NZa',
  'Codetabel': 'CL_HOOFDBEROEPEN_GBG',
  'DDID': '4034',
  'Eind': '80',
  'Lengte': '20',
  'Naam': 'Beroepcode 1e hoofdbehandelaar',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '81',
  'Code org': 'Vektis',
  'Codetabel': 'AGB (persoonlijke zorgverleners code)',
  'DDID': '4035',
  'Eind': '88',
  'Lengte': '8',
  'Naam': '2e hoofdbehandelaar',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'O'},
 {'Begin': '89',
  'Code org': 'NZa',
  'Codetabel': 'CL_HOOFDBEROEPEN_GBG',
  'DDID': '4036',
  'Eind': '108',
  'Lengte': '20',
  'Naam': 'Beroepcode 2e hoofdbehandelaar',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'O'},
 {'Begin': '109',
  'Code org': '',
  'Codetabel': '',
  'DDID': '4172',
  'Eind': '109',
  'Lengte': '1',
  'Naam': 'Experimenteerruimte',
  'Patroon': "'J', 'N', [spatie]",
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'O'},
 {'Begin': '110',
  'Code org': 'Vektis',
  'Codetabel': 'COD327-VEK1 (volwassenen)',
  'DDID': '3331',
  'Eind': '111',
  'Lengte': '2',
  'Naam': 'Verwijstype/code (zelf)verwijzer',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'CV'},
 {'Begin': '112',
  'Code org': 'Vektis',
  'Codetabel': 'AGB (persoonlijke zorgverleners code)',
  'DDID': '3264',
  'Eind': '119',
  'Lengte': '8',
  'Naam': 'Verwijzer',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'CV'},
 {'Begin': '120',
  'Code org': 'Vektis',
  'Codetabel': 'COD016',
  'DDID': '3265',
  'Eind': '123',
  'Lengte': '4',
  'Naam': 'Soort verwijzer',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'CV'},
 {'Begin': '124',
  'Code org': '',
  'Codetabel': '',
  'DDID': '4045',
  'Eind': '131',
  'Lengte': '8',
  'Naam': 'Verwijsdatum',
  'Patroon': 'YYYYMMDD',
  'Sleutel': '',
  'Type': 'D',
  'Verplicht': 'O'},
 {'Begin': '132',
  'Code org': '',
  'Codetabel': '',
  'DDID': '4046',
  'Eind': '132',
  'Lengte': '1',
  'Naam': 'Stoornis DSM-IV',
  'Patroon': "'J' of 'N' of [spatie]",
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'O'},
 {'Begin': '133',
  'Code org': 'NZa',
  'Codetabel': 'CL_DIAGNOSE_GBG',
  'DDID': '3266',
  'Eind': '152',
  'Lengte': '20',
  'Naam': 'Diagnosecode',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'CV'},
 {'Begin': '153',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3267',
  'Eind': '160',
  'Lengte': '8',
  'Naam': 'Diagnosedatum',
  'Patroon': 'YYYYMMDD',
  'Sleutel': '',
  'Type': 'D',
  'Verplicht': 'CV'},
 {'Begin': '161',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3268',
  'Eind': '161',
  'Lengte': '1',
  'Naam': 'ROM toegepast',
  'Patroon': "'J' of 'N'",
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '162',
  'Code org': 'NZa',
  'Codetabel': '',
  'DDID': '3269',
  'Eind': '167',
  'Lengte': '6',
  'Naam': 'Prestatiecode verwacht',
  'Patroon': '',
  'Sleutel': 'CL_PRESTATIES_GBG',
  'Type': 'AN',
  'Verplicht': 'CV'},
 {'Begin': '168',
  'Code org': 'NZa',
  'Codetabel': '',
  'DDID': '3333',
  'Eind': '173',
  'Lengte': '6',
  'Naam': 'Prestatiecode geleverd',
  'Patroon': '',
  'Sleutel': 'CL_PRESTATIES_GBG',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '174',
  'Code org': '',
  'Codetabel': '',
  'DDID': '4044',
  'Eind': '183',
  'Lengte': '10',
  'Naam': 'Verwachte prestatie',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'O'},
 {'Begin': '184',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3270',
  'Eind': '194',
  'Lengte': '11',
  'Naam': 'Verkoopprijs',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'N',
  'Verplicht': 'V'},
 {'Begin': '195',
  'Code org': 'Vektis',
  'Codetabel': '',
  'DDID': '3271',
  'Eind': '198',
  'Lengte': '4',
  'Naam': 'Zorgverzekeraarcode',
  'Patroon': '',
  'Sleutel': 'UZOVI register',
  'Type': 'AN',
  'Verplicht': 'O'},
 {'Begin': '199',
  'Code org': 'NZa',
  'Codetabel': '',
  'DDID': '3272',
  'Eind': '218',
  'Lengte': '20',
  'Naam': 'Reden sluiten code',
  'Patroon': '',
  'Sleutel': 'CL_REDENSLUITEN_GBG',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '219',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3273',
  'Eind': '226',
  'Lengte': '8',
  'Naam': 'Declaratiedatum',
  'Patroon': 'YYYYMMDD',
  'Sleutel': '',
  'Type': 'D',
  'Verplicht': 'O'},
 {'Begin': '227',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3349',
  'Eind': '229',
  'Lengte': '3',
  'Naam': 'Zorgvraagzwaarte',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'O'},
 {'Begin': '230',
  'Code org': '',
  'Codetabel': '',
  'DDID': '4052',
  'Eind': '249',
  'Lengte': '20',
  'Naam': 'Reserve',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'O'}]

format_zorgprofiel = [{'Begin': '1',
  'Codeorg': '',
  'Codetabel': '',
  'DDID': '3310',
  'Eind': '20',
  'Lengte': '20',
  'Naam': 'Behandelcomponentnummer',
  'Patroon': '',
  'Sleutel': 'PK',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '21',
  'Codeorg': '',
  'Codetabel': '',
  'DDID': '3309',
  'Eind': '40',
  'Lengte': '20',
  'Naam': 'Behandeltrajectnummer',
  'Patroon': '',
  'Sleutel': 'FK',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '41',
  'Codeorg': 'NZa',
  'Codetabel': 'CL_BEHANDELCOMPONENTEN_GBG',
  'DDID': '3311',
  'Eind': '60',
  'Lengte': '20',
  'Naam': 'Behandelcomponentcode',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '61',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3312',
  'Eind': '68',
  'Lengte': '8',
  'Naam': 'Behandelcomponentdatum',
  'Patroon': 'YYYYMMDD',
  'Sleutel': '',
  'Type': 'D',
  'Verplicht': 'V'},
 {'Begin': '69',
  'Code org': 'Vektis',
  'Codetabel': 'AGB (persoonlijke zorgverleners code)',
  'DDID': '3313',
  'Eind': '76',
  'Lengte': '8',
  'Naam': 'Behandelaarcode',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'O'},
 {'Begin': '77',
  'Codeorg': 'NZa',
  'Codetabel': 'CL_BEROEP_GBG of CL_HOOFDBEROEPEN_GBG',
  'DDID': '3314',
  'Eind': '96',
  'Lengte': '20',
  'Naam': 'Beroepcode',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '97',
  'Codeorg': '',
  'Codetabel': '',
  'DDID': '4051',
  'Eind': '97',
  'Lengte': '1',
  'Naam': 'Hoofdbehandelaar',
  'Patroon': "'J' of 'N' of[spatie]",
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'CV'},
 {'Begin': '98',
  'Codeorg': '',
  'Codetabel': '',
  'DDID': '3315',
  'Eind': '103',
  'Lengte': '6',
  'Naam': 'Direct patientgebonden tijd (minuten)',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'N',
  'Verplicht': 'V'},
 {'Begin': '104',
  'Codeorg': '',
  'Codetabel': '',
  'DDID': '3355',
  'Eind': '109',
  'Lengte': '6',
  'Naam': 'Indirect patientgebonden tijd - reistijd(minuten)',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'N',
  'Verplicht': 'O'},
 {'Begin': '110',
  'Codeorg': '',
  'Codetabel': '',
  'DDID': '3316',
  'Eind': '115',
  'Lengte': '6',
  'Naam': 'Indirect patientgebonden tijd - algemeen(minuten)',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'N',
  'Verplicht': 'V'},
 {'Begin': '116',
  'Codeorg': '',
  'Codetabel': '',
  'DDID': '3348',
  'Eind': '135',
  'Lengte': '20',
  'Naam': 'Afspraaknummer/code',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'O'},
 {'Begin': '136',
  'Codeorg': '',
  'Codetabel': '',
  'DDID': '4053',
  'Eind': '155',
  'Lengte': '20',
  'Naam': 'Reserve',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'O'},
 {'Begin': '',
  'Codeorg': '',
  'Codetabel': '',
  'DDID': '36',
  'Eind': '',
  'Lengte': '',
  'Naam': '',
  'Patroon': '',
  'Sleutel': '',
  'Type': '',
  'Verplicht': ''}]


format_pakbon = [{'Begin': '1',
  'Code org': 'Vektis',
  'Codetabel': 'AGB (praktijk ofinstellingscode)',
  'DDID': '3362',
  'Eind': '8',
  'Lengte': '8',
  'Naam': 'Declarerende instelling',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '9',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3371',
  'Eind': '10',
  'Lengte': '2',
  'Naam': 'Instelling volgnr DIS',
  'Patroon': 'NN',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '11',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3337',
  'Eind': '14',
  'Lengte': '4',
  'Naam': 'Versienummer GA',
  'Patroon': 'NN.N',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '15',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3233',
  'Eind': '22',
  'Lengte': '8',
  'Naam': 'Creatiedatum',
  'Patroon': 'YYYYMMDD',
  'Sleutel': '',
  'Type': 'D',
  'Verplicht': 'V'},
 {'Begin': '23',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3234',
  'Eind': '24',
  'Lengte': '2',
  'Naam': 'Volgnummer',
  'Patroon': 'NN',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '25',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3344',
  'Eind': '72',
  'Lengte': '48',
  'Naam': 'Zipfilenaam',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '73',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3339',
  'Eind': '87',
  'Lengte': '15',
  'Naam': 'Softwareleverancier',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '88',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3334',
  'Eind': '102',
  'Lengte': '15',
  'Naam': 'Softwarepakket',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '103',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3342',
  'Eind': '117',
  'Lengte': '15',
  'Naam': 'Softwareversie',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '118',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3239',
  'Eind': '124',
  'Lengte': '7',
  'Naam': 'Aantal patient',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'N',
  'Verplicht': 'V'},
 {'Begin': '125',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3345',
  'Eind': '131',
  'Lengte': '7',
  'Naam': 'Aantal behandeltraject',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'N',
  'Verplicht': 'V'},
 {'Begin': '132',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3245',
  'Eind': '138',
  'Lengte': '7',
  'Naam': 'Aantal geleverd zorgprofiel',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'N',
  'Verplicht': 'V'},
 {'Begin': '139',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3346',
  'Eind': '145',
  'Lengte': '7',
  'Naam': 'Aantal overige verrichting',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'N',
  'Verplicht': 'V'},
 {'Begin': '146',
  'Code org': '',
  'Codetabel': '',
  'DDID': '3341',
  'Eind': '159',
  'Lengte': '14',
  'Naam': 'Gebruikersnaam',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'V'},
 {'Begin': '160',
  'Code org': 'Kamer vanKoophandel',
  'Codetabel': 'KvK registratie',
  'DDID': '3361',
  'Eind': '167',
  'Lengte': '8',
  'Naam': 'Kamer van Koophandelnummer',
  'Patroon': '',
  'Sleutel': '',
  'Type': 'AN',
  'Verplicht': 'O'}]








